version: "3.8"
services:
  caffmed:
    build: .
    container_name: caffmed-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MODEL_PATH=model/model.h5
      - THRESHOLD=0.85
      - MAX_CONTENT_LENGTH=5242880
      - CLASS_NAMES=Glioma detected,Meningioma detected,Pituitary detected,No Tumor detected
    volumes:
      - .:/app
    restart: unless-stopped