name: Caffmed CI

on:
  push:
    branches:
      - main
      - backend/development
      - frontend/development
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  backend:
    needs: changes
    if: |
      contains(github.event.head_commit.message, '[BE]') ||
      contains(github.event.head_commit.message, '[ALL]') ||
      (github.event_name == 'pull_request' && needs.changes.outputs.backend == 'true')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --disable-warnings

  frontend:
    needs: changes
    if: |
      contains(github.event.head_commit.message, '[FE]') ||
      contains(github.event.head_commit.message, '[ALL]') ||
      (github.event_name == 'pull_request' && needs.changes.outputs.frontend == 'true')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: lint code
        run: npm run lint

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build project
        run: npm run build
